export const ON_START_DATE_CHANGE = 'ON_START_DATE_CHANGE';
export const ON_END_DATE_CHANGE = 'ON_END_DATE_CHANGE';
export const ON_NAME_CHANGE = 'ON_NAME_CHANGE';
export const ON_SEARCH = 'ON_SEARCH';